---
version: "3"
services:
  app:
    build: .
    image: ghcr.io/luketainton/urls:latest
    restart: unless-stopped
    volumes:
      - /path/to/urls.php:/var/www/urls.php:ro
    ports:
      - 8000:80